services:
# ======================== Build Images ===========================
  ros2_base:
    build:
      context: .
      tags: 
        - "ros2_img:latest"
      target: ros2_img
    entrypoint: ["sh", "-c", "exit"]

  robostore:
    build:
      context: .
      tags: 
        - "robostore_img:latest"
      target: robostore_img
    depends_on:
      ros2_base:
        condition: service_completed_successfully
    entrypoint: ["sh", "-c", "exit"]

  platform_env:
    container_name: robostore_platform
    image: robostore_img:latest
    stdin_open: true
    tty: true       
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
    network_mode: "host"
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

# To be continued...