camera_manager:
  ros__parameters:
    sim: false
    camera_id: [1, 2]
    image_topic: [
      "/left_camera/realsense/color/image_raw", 
      "/right_camera/realsense/color/image_raw"
      ]
    pointcloud_topic: [
      "/left_camera/realsense/depth/color/points", 
      "/right_camera/realsense/depth/color/points"
      ]

data_saver:
  ros__parameters:
    workspace_name: "robostore_upper_ws"
    save_folder_name: "vision_data"

web_video_server:
  ros__parameters:
    port: 18080
    address: '192.168.8.101'
    server_threads: 4
    ros_threads: 4
    # default_stream_type: 'h264'
  