action_planner:
  ros__parameters:
    sim: false
    eef_offset: [0.0, 0.0, 0.0]
    pre_obj_pose_shift: 0.05
    pre_place_pose_shift: 0.06
    post_pick_lift_offset: 0.05 # 0.02
    post_pick_back_offset: 0.2 # 0.1 
    post_place_down_offset: 0.01

motion_planner:
  ros__parameters:
    sim: false
    max_pick_attempt: 2
    move_to_srv_names: ["home_pose", "middle_pose", "scan_pose", "pre_pick_pose", "pre_place_pose"]

collision_planner:
  ros__parameters:
    sim: false
    import_from_file: true

workflow_planner:
  ros__parameters:
    max_pick_attampt: 2
    valid_z_threshold: 0.1 # filter invalid vision recognition result
    max_scan_attempt: 2
    re_scan_translation: 0.02
    place_offset: 0.01
    # 20250818
    # eef_to_left_camera: [-0.11428286, 0.00178735, -0.05448768, -0.00511073, 0.01296962, 0.71294748, -0.70107886]
    # 20250820
    # eef_to_left_camera: [-0.11041817, -0.00236401, -0.03587768, -0.00683415, 0.00986319, 0.70991133, -0.70418883]
    eef_to_left_camera: [-0.11041817, 0.00236401, -0.04448768, -0.00683415, 0.00986319, 0.70991133, -0.70418883]

vacuum_gripper_ctlr:
  ros__parameters:
    sim: false
    leak_threshold: -50000.0 # unit: Pa

robot_controller:
  ros__parameters:
    group_name: arm # defined in the autostore for nachi mz07l 
    eef_name: tcp
    default_eef_step: 0.05
    default_jump_threshold: 3.5
    
nachi_robot:
  ros__parameters:
    sim: true
    model: "mz07L"
    ip: "192.168.2.10"

vacuum_gripper:
  ros__parameters:
    sim: false
    can_id: 0x55

    # valve
    no_of_channel: 2

    # ultrasonic sensor
    enable_ultrasonic: true
    field_of_view: 0.3
    min_range: 0.05
    max_range: 0.5

