/**:
  ros__parameters:
    sim: false

manager:
  ros__parameters:
    rotation_name: ["abs_back", "abs_front", "abs_left", "abs_right", "relative_back", "relative_left", "relative_right"]
    arm_poses_name: ["home", "holding", "action"]

action_planner:
  ros__parameters:
    # sim: false
    eef_offset: [0.0, 0.0, 0.0] # manual offset
    obj_pose_offset: 0.0075
    pre_obj_pose_shift: 0.1
    pre_place_pose_shift: 0.15
    post_pick_lift_offset: 0.02
    post_pick_back_offset: 0.25
    post_place_down_offset: 0.01

motion_planner:
  ros__parameters:
    # sim: false
    enable_ultrasonic: false
    max_pick_attempt: 2

    left_zero_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    left_home_joints: [0.6909, 1.3581, -1.2883, -1.8352, 0.0238, -0.4530, 0.3616]
    # left_holding_joints: [-0.1290, 0.8766, -0.2334, -1.7444, 0.3358, 1.0115, 1.0033]
    left_holding_joints: [1.1825, 1.4336, -1.3192, -1.9627, 1.5372, 0.2839, -0.8126]
    left_action_joints: [-0.3649, 0.8048, -0.1931, -2.0853, 0.4905, 1.2842, 0.6162]

    right_zero_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    right_home_joints: [-0.6909, 1.3581, 1.2883, -1.8352, 0.0238, -0.4530, -0.3616]
    # right_holding_joints: [0.1290, 0.8766, 0.2334, -1.7444, -0.3358, 1.0115, -1.0033]
    right_holding_joints: [-1.1825, 1.4336, 1.3192, -1.9627, -1.5372, 0.2839, -0.8126]
    right_action_joints: [0.3649, 0.8048, 0.1931, -2.0853, -0.4905, 1.2842, -0.6162]

collision_planner:
  ros__parameters:
    # sim: false
    import_from_file: true

workflow_planner:
  ros__parameters:
    # sim: false
    max_pick_attempt: 2
    valid_z_threshold: 0.1 # filter invalid vision recognition result
    max_scan_attempt: 2
    re_scan_x_translation: 0.02
    re_scan_y_translation: 0.1
    place_offset: 0.01
    scan_x_distance: 0.025
    scan_z_distance: 0.27
    optimal_arm_flat_height_distance: 0.2
    table_front_offset: 0.6
    table_height_offset: 0.1
    tcp_to_left_camera: [0.090, -0.032, -0.100, 0.02, -0.003, 0.707, 0.707]
    tcp_to_right_camera: [0.090, -0.032, -0.116, 0.002, -0.003, 0.713, 0.702]

fold_elevator_driver:
  ros__parameters:
    home: [0.7192, -1.4436, -0.7244, 0.0]
    rack_2: [0.0, 0.0, 0.0, 0.0]
    rack_3: [0.0, 0.0, 0.0, 0.0]
    rack_4: [0.0, 0.0, 0.0, 0.0]

vacuum_gripper:
  ros__parameters:
    # sim: false
    leak_threshold: -35000.0 # unit: Pa

/left_arm/robot_controller:
  ros__parameters:
    group_name: "left_arm"
    eef_name: "left_tcp"
    ref_frame: "base_footprint"
    default_eef_step: 0.005
    default_jump_threshold: 5.0

/left_action_arm/robot_controller:
  ros__parameters:
    group_name: "left_action_arm"
    eef_name: "left_tcp"
    ref_frame: "base_footprint"
    default_eef_step: 0.005
    default_jump_threshold: 5.0

/right_arm/robot_controller:
  ros__parameters:
    group_name: "right_arm"
    eef_name: "right_tcp"
    ref_frame: "base_footprint"
    default_eef_step: 0.005
    default_jump_threshold: 5.0

/right_action_arm/robot_controller:
  ros__parameters:
    group_name: "right_action_arm"
    eef_name: "right_tcp"
    ref_frame: "base_footprint"
    default_eef_step: 0.005
    default_jump_threshold: 5.0

/fold_elevator/robot_controller:
  ros__parameters:
    group_name: "fold_elevator"
    eef_name: "link4"
    ref_frame: "base_footprint"
    default_eef_step: 0.005
    default_jump_threshold: 5.0

tf_broadcaster:
  ros__parameters:
    rack_1_shelf_1: [ 0.0 ]
    rack_1_shelf_2: [ 0.22, 0.37, 0.90 ]
    rack_1_shelf_3: [ 0.22, 0.37, 0.61, 0.79, 0.92, 1.05 ]
    rack_1_shelf_4: [ 0.22, 0.37, 0.61, 0.79, 0.92, 1.05 ]
    left_tcp_to_camera: [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 ]
    right_tcp_to_camera: [ 0.08855604, -0.03328494, -0.11521747, -0.00347244, -0.00389369, 0.70516316, 0.70902588 ]

gripper:
  ros__parameters:
    # sim: false
    can_id: 0x55
    can_namespace: "upper_orin"
    can_interface: "can2"

    # clip
    enable_clip: true
    min_gripper_force: 20
    max_gripper_force: 100
    min_gripper_position: 0.0
    max_gripper_position: 95.0

    # ultrasonic sensor
    enable_ultrasonic: false
    field_of_view: 0.3
    min_range: 0.05
    max_range: 0.5

    # vaccum pressure
    leak_threshold: -35000.0   # unit: Pa



